# 这是一个配置文件范例.
# 所有账户信息为生成, 请填写您的账户信息.
# 查看帮助与详情: https://emby-keeper.github.io#安装与使用

# 每天进行 Telegram Bot 签到的时间范围, 等同于命令行 "-c" 参数.
time = "<8:00AM,10:00AM>"

# 每隔几天进行 Emby 保活, 或随机范围, 等同于命令行 "-e" 参数.
interval = "<3,12>"

# Emby 保活开始时间的时间范围.
watchtime = "<11:00AM,11:00PM>"

# 将关键信息发送到第一个 Telegram 账号, 设为 N 以发送到第 N 个.
notifier = true

# 每个 Telegram Bot 签到的最大尝试时间 (秒).
timeout = 240

# 每个 Telegram Bot 签到的最大尝试次数.
retries = 4

# 最大可同时进行的 Telegram Bot 签到.
concurrent = 1

# 最大可同时进行的 Emby 站点保活.
watch_concurrent = 3

# 计划任务时, 各站点之间签到的随机时间差异 (分钟), 所有站点签到将在该时间范围内完成.
random = 60

# 代理设置, Emby 和 Telegram 均将通过此代理连接, 服务器位于国内时请配置代理并取消注释.
# 详见: https://emby-keeper.github.io/guide/配置文件#proxy-子项
# [proxy]
# hostname = "127.0.0.1"
# port = 1080
# scheme = "socks5" # 可选: http / socks5

# 服务设置, 当您需要禁用某些站点时, 请将该段取消注释并修改.
# 该部分内容是根据 Embykeeper 6.3.0 生成的.
# 详见: https://emby-keeper.github.io/guide/配置文件#service-子项
# 使用 checkiner = ["all"] 以启用所有签到器, 使用 checkiner = ["sgk"] 以启用所有社工库签到器.

# 默认启用站点:
# [service]
# checkiner = ["apoppro", "aurora", "awatv", "cc", "datasgk", "dvfilm", "feiyue", "feiyuedpx", "future", "ikunmusic", "jsq", "levilde", "lily", "lyrebird", "magic", "micu", "misty", "mjj", "mooncake", "moonkk", "nebula", "pandatv", "pandatv_group", "peach", "pilipili", "plumber", "pornemby", "raismusic", "saturday", "sfcju", "shufu", "tanhua", "tdck", "terminus", "tiannan", "tiannanus", "watermelon", "worldline", "yomo", "zm"]
# monitor = ["bgk", "future", "infinity_fly", "misty", "pornemby_alert", "pornemby_answer", "pornemby_double", "pornemby_dragon_rain", "pornemby_nohp", "viper"]
# messager = []

# 全部可用站点:
# [service]
# checkiner = ["agentsgk", "aisgk", "aivbi", "akile", "akile_group", "akuai", "alpha", "apop", "apoppro", "aurora", "awamusic", "awatv", "baidusgk", "bearsgk", "bingdaosgk", "bitsgk", "bluesea", "bostsgk", "bytevirt_group", "carll1sgk", "carll2sgk", "cc", "charon", "charon_old", "chunjiangsgk", "ciji", "datasgk", "dingdangsgk", "dogsgk", "dvfilm", "embyhub", "fanhuasgk", "feiji", "feiyue", "feiyuedpx", "feiyuemusic", "feiyuemusic_group_old", "future", "happy", "heisi", "hka", "huasgk", "ikunmusic", "infsgk", "ingeeksgk", "jinding", "jms", "jms_iptv", "jms_old", "johnsgk", "jsq", "judog", "koisgk", "levilde", "lily", "ljyy", "ljyy_old", "lyrebird", "m78", "magic", "marmot_group_old", "mastersgk", "micu", "minisgk", "misty", "mjj", "mooncake", "moonkk", "moshensgk", "nebula", "niaoge", "pandatv", "pandatv_group", "peach", "pilipili", "pingansgk", "plumber", "pornemby", "qingfengsgk", "raismusic", "rednosesgk", "saturday", "seedsgk", "sfcju", "shufu", "shzi", "singularity", "skysink", "sssq", "starcat", "starsgk", "tanhua", "tdck", "temby", "temby_beta", "temby_old", "terminus", "terminus_old", "theend", "tianmaosgk", "tiannan", "tiannanus", "unionsgk", "watermelon", "worldline", "xraysgk", "yomo", "zhihusgk", "zhipian", "zhushousgk", "zm"]
# monitor = ["bgk", "embyhub", "follow", "future", "infinity_fly", "judog", "misty", "polo", "pornemby_alert", "pornemby_answer", "pornemby_double", "pornemby_dragon_rain", "pornemby_nohp", "pornemby_register", "shufu", "terminus_exam", "viper"]
# messager = ["marmot", "nakonako", "pornemby", "smart_pornemby"]

# Telegram 账号设置, 您可以重复该片段多次以增加多个账号.
# 详见: https://emby-keeper.github.io/guide/配置文件#telegram-子项

[[telegram]]
phone = "+8616380798084"
checkin = true
send = false # 启用该账号的自动水群功能 (需要高级账号, 谨慎使用)
monitor = false # 启用该账号的自动监控功能 (需要高级账号)

[[telegram]]
phone = "+8617610948341"
checkin = true
send = false # 启用该账号的自动水群功能 (需要高级账号, 谨慎使用)
monitor = false # 启用该账号的自动监控功能 (需要高级账号)

# Emby 账号设置, 您可以重复该片段多次以增加多个账号.
# 详见: https://emby-keeper.github.io/guide/配置文件#emby-子项

[[emby]]
url = "https://www.mccarthy.com/"
username = "rmcgrath"
password = ")3XLC1yESG"
time = [120, 240] # 模拟观看的时长范围 (秒)

[[emby]]
url = "https://www.castillo.info/"
username = "moorejesse"
password = "jO05F_b&(j"
time = [120, 240] # 模拟观看的时长范围 (秒)
